#!/bin/bash

VERSION=`(git describe --always --long --dirty 2>/dev/null || echo "unknown")`
REVISION=`(git rev-parse HEAD)`

cat >Version.java <<EOF
// This file is automatically generated. Do not edit.
package main;
class Version {
  public static String version = "$VERSION";
  public static String revision = "$REVISION";
}
EOF
