stationsplein.net.xml : stationsplein.nod.xml stationsplein.edg.xml stationsplein.con.xml
	netconvert --simple-projection --node-files=stationsplein.nod.xml --edge-files=stationsplein.edg.xml --connection-files=stationsplein.con.xml --output-file=stationsplein.net.xml
