stationsplein.net.xml : stationsplein.nod.xml stationsplein.edg.xml
	netconvert --simple-projection --node-files=stationsplein.nod.xml --edge-files=stationsplein.edg.xml --output-file=stationsplein.net.xml
